'use strict';
const $=id=>document.getElementById(id);
const fragment=new URLSearchParams(location.hash.slice(1));
if(fragment.get('key')){sessionStorage.setItem('station-bridge-key',fragment.get('key'));history.replaceState(null,'',location.pathname);}
const key=sessionStorage.getItem('station-bridge-key')||'';
let state={},advanced={},devices=[],busy=false,pollBusy=false,deviceSignature='',peerSignature='',endpointSignature='',outputSignature='',qrURL='',activeMode='';
const selected=new Set();
function notice(text,error=false){$('notice').textContent=text;$('notice').hidden=false;$('notice').classList.toggle('error',error);}
async function request(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:{'X-Bridge-Key':key,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined,cache:'no-store'});let b;try{b=await r.json();}catch{throw Error('Приложение недоступно. Откройте значок рядом с часами.');}if(!r.ok)throw Error(b.error||`HTTP ${r.status}`);return b;}
function controls(){const live=state.media?.kind==='live',connected=!!state.station?.connected,active=busy||state.busy;for(const id of ['login','logout','scan','all','connect','bind','nativeRefresh','rename','installDriver','start','test','mode','endpoint','legacyOutput'])$(id).disabled=!!active;
$('connect').disabled ||= !state.auth?.logged_in||live;$('start').disabled ||= !connected||live;$('test').disabled ||= !connected||live;
for(const id of ['bind','rename','installDriver','endpoint','legacyOutput','mode'])$(id).disabled ||= live;
$('rename').disabled ||= !advanced.native_audio?.selected?.virtual_cable;$('master').disabled=!advanced.native_audio?.selected;$('mute').disabled=$('master').disabled;
$('stop').disabled=!connected&&!state.media?.active;$('live').disabled=!live||active;$('file').disabled=!connected||active;
$('legacyOutputLabel').hidden=!!advanced.native_audio?.selected;}
async function execute(command,data={},group=false){busy=true;controls();try{return await request(group?'/api/advanced':'/api/action',{command,...data});}catch(e){notice(e.message,true);throw e;}finally{busy=false;controls();}}
function bind(id,fn){$(id).addEventListener('click',()=>Promise.resolve().then(fn).catch(()=>{}));}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function renderDevices(){const combined=new Map();for(const d of advanced.saved_group||[])combined.set(d.id,{...d});for(const d of state.devices||[])combined.set(d.id,{...(combined.get(d.id)||{}),...d});const next=[...combined.values()];const sig=JSON.stringify(next);if(sig===deviceSignature)return;deviceSignature=sig;devices=next;
if(!selected.size&&!$('devices').dataset.initialized){for(const d of advanced.saved_group||[])selected.add(d.id);$('devices').dataset.initialized='yes';}
$('devices').replaceChildren();if(!devices.length){$('devices').append(el('p','Войдите и запустите поиск.','hint'));return;}
for(const d of devices){const box=el('div',undefined,'device'),label=el('label'),check=document.createElement('input');check.type='checkbox';check.checked=selected.has(d.id);check.onchange=()=>check.checked?selected.add(d.id):selected.delete(d.id);check.dataset.device=d.id;label.append(check,document.createTextNode(d.name||'Станция'));box.append(label,el('small',(d.host||'IP не найден')+' · '+(d.platform||'platform не найден')));
const details=el('details');details.append(el('summary','Адреса подключения'));for(const [field,caption] of [['host','IP колонки'],['audioHost','IP компьютера для этой колонки (пусто — автоматически)']]){const l=el('label',caption,'field'),input=document.createElement('input');input.type='text';input.value=d[field]||'';input.placeholder=field==='host'?'192.168.1.64':'Автоматически';input.onchange=()=>d[field]=input.value.trim();l.append(input);details.append(l);}box.append(details);$('devices').append(box);}}
function renderPeers(force=false){if(!force&&$('peers').contains(document.activeElement))return;const rows=advanced.peers||[];const sig=JSON.stringify(rows.map(p=>[p.device.id,p.state,p.media.requests,p.media.requested_mb,p.peer_approval,p.error]));if(sig===peerSignature)return;peerSignature=sig;$('peers').replaceChildren();for(const p of rows){const box=el('article',undefined,'peer');box.append(el('h3',p.device.name));const s=p.state||{},m=p.media||{};box.append(el('p',`${s.connected?'Подключена':'Нет соединения'} · ${p.device.host} · HTTP ${m.port||8808}\n${s.playing?'Играет':'Ожидает'} · ${m.requests||0} запросов · ${m.requested_mb||0} МБ`, 'stats'));
const label=el('label',`Громкость Станции: ${Math.round((s.volume||0)*100)}%`),range=document.createElement('input');range.type='range';range.min=0;range.max=100;range.step=10;range.value=Math.round((s.volume||0)*100);range.setAttribute('aria-label','Громкость '+p.device.name);range.oninput=()=>label.textContent=`Громкость Станции: ${range.value}%`;range.onchange=()=>execute('station_volume',{id:p.device.id,value:Number(range.value)/100},true).catch(()=>{});box.append(label,range);
if(p.error)box.append(el('p',p.error,'hint'));
if(p.peer_approval){const a=p.peer_approval,nat=el('div',undefined,'nat');nat.append(el('p',`Запрос аудио пришёл от ${a.peer||a.ip}. Разрешайте только ожидаемый адрес вашего маршрутизатора.`));const button=el('button','Разрешить адрес и повторить');button.onclick=()=>{if(confirm(`Разрешить ${a.peer||a.ip} для «${p.device.name}»?`))execute('peer_approve',{id:p.device.id,ip:a.peer||a.ip,challenge:a.challenge},true).catch(()=>{});};nat.append(button);box.append(nat);} $('peers').append(box);}}
function renderNative(){const n=advanced.native_audio||{},sig=JSON.stringify(n.endpoints||[]);if(sig!==endpointSignature){const prior=$('endpoint').value;endpointSignature=sig;$('endpoint').replaceChildren(new Option('Не привязан · прежний loopback',''));for(const d of n.endpoints||[])$('endpoint').add(new Option((d.virtual_cable?'Виртуальный · ':'')+d.name,d.id));$('endpoint').value=n.selected?.id||prior;}
if(n.selected&&!$('endpoint').value)$('endpoint').value=n.selected.id;
$('endpointStatus').textContent=n.selected?`Используется: ${n.selected.name}. В Windows выберите этот же выход для музыки.`:(n.error||'Привяжите виртуальный выход. До установки драйвера доступен прежний захват физического выхода.');
if(document.activeElement!==$('master'))$('master').value=Math.round((n.selected?.volume||0)*100);$('masterLabel').textContent=n.selected?`${Math.round(n.selected.volume*100)}%`:'—';$('mute').textContent=n.selected?.mute?'Вернуть звук':'Без звука';}
function playbackData(){const o=(state.outputs||[]).find(d=>String(d.index)===$('legacyOutput').value)||{};const mode=$('mode').value;return {device_index:o.index,device_key:o.key,playback_mode:mode.startsWith('fallback')?'fallback':mode,transport:mode==='fallback_hls'?'hls':mode==='fallback_mp3'?'mp3':'pcm',latency_profile:mode==='experimental'?'experimental':'fast',segment_time:1};}
async function poll(){if(pollBusy)return;pollBusy=true;try{[state,advanced]=await Promise.all([request('/api/state'),request('/api/advanced')]);$('version').textContent=advanced.version;
$('account').textContent=state.auth?.logged_in?'Яндекс подключён · '+(state.auth.name||'аккаунт владельца'):'Войдите в аккаунт владельца Станций';if(state.auth?.logged_in){$('qr').hidden=true;if(qrURL){URL.revokeObjectURL(qrURL);qrURL='';}}
renderDevices();renderPeers();renderNative();const sig=JSON.stringify(state.outputs||[]);if(sig!==outputSignature){const v=$('legacyOutput').value;outputSignature=sig;$('legacyOutput').replaceChildren();for(const o of state.outputs||[])$('legacyOutput').add(new Option(o.name,o.index));if(v)$('legacyOutput').value=v;}
const live=state.media?.kind==='live',opts=state.live_options||{};if(live){const mode=opts.playback_mode||'main';const sig=JSON.stringify(opts);if(activeMode!==sig){$('mode').value=mode==='fallback'?'fallback_'+opts.transport:mode;activeMode=sig;}}else activeMode='';
const m=state.media||{};$('streamStatus').textContent=live?`Передача: ${m.transport?.toUpperCase()} · ${advanced.peers?.length||0} колонок · ${m.capture?.device?.name||m.capture?.source||''}`:'Трансляция остановлена. Запуск — только по вашей команде.';
$('meter').value=m.capture?.level||0;if(document.activeElement!==$('interval'))$('interval').value=String(state.continuity?.maintenance?.interval_seconds??240);
$('log').textContent=(state.logs||[]).map(l=>`${l.time}  ${l.text}`).join('\n');controls();
}catch(e){notice(e.message,true);}finally{pollBusy=false;}}
bind('login',async()=>{const r=await execute('qr',{remember:$('remember').checked});if(qrURL)URL.revokeObjectURL(qrURL);qrURL=URL.createObjectURL(new Blob([r.svg],{type:'image/svg+xml'}));const image=new Image();image.src=qrURL;image.alt='QR для входа в Яндекс';$('qr').replaceChildren(image);$('qr').hidden=false;});
bind('logout',()=>execute('logout'));
bind('scan',()=>execute('scan'));
bind('all',()=>{for(const d of devices)selected.add(d.id);for(const c of $('devices').querySelectorAll('input[type=checkbox]'))c.checked=true;});
bind('connect',async()=>{const list=devices.filter(d=>selected.has(d.id));const overrides={};for(const d of list)if(d.audioHost)overrides[d.id]=d.audioHost;let r=await execute('connect_group',{devices:list,overrides},true);if(r.trust_required){const text=r.trust.map(t=>`${t.device.name}\n${t.device.host}:${t.device.port}\nSHA-256: ${t.fingerprint}${t.changed?'\nВНИМАНИЕ: сертификат изменился':''}`).join('\n\n');if(!confirm('Проверьте колонки и подтвердите сертификаты:\n\n'+text)){await execute('cancel_group_trust',{},true);return;}const accepted={};for(const t of r.trust)accepted[t.device.id]=t.fingerprint;r=await execute('connect_group',{devices:list,overrides,accepted},true);}if(r.results)notice(`Подключено ${r.results.filter(x=>x.connected).length} из ${r.results.length}. Проверьте тестовый сигнал.`);});
bind('bind',()=>execute('bind_endpoint',{id:$('endpoint').value},true));
bind('nativeRefresh',()=>execute('native_refresh',{},true));
bind('soundSettings',()=>execute('sound_settings',{},true));
bind('installDriver',()=>{if(confirm('Открыть загрузку оригинального VB-CABLE с vb-audio.com? Это отдельный драйвер с собственной лицензией. Для установки появится окно производителя и UAC; возможна перезагрузка.'))return execute('install_driver',{confirmed:true},true);});
bind('firewall',()=>{if(confirm('Создать ограниченные правила Windows Firewall только для Python этого приложения, выбранных адресов и портов группы, профиль Private?'))return execute('firewall',{confirmed:true},true);});
bind('rename',()=>{if(confirm('Переименовать выбранный виртуальный выход в Yandex Station Advanced? Windows запросит права администратора.'))return execute('rename_endpoint',{confirmed:true},true);});
$('master').oninput=()=>$('masterLabel').textContent=$('master').value+'%';$('master').onchange=()=>execute('master_volume',{value:Number($('master').value)/100},true).catch(()=>{});
bind('mute',()=>execute('master_mute',{value:!advanced.native_audio?.selected?.mute},true));
bind('start',()=>execute('live',playbackData()));bind('stop',()=>execute('stop'));bind('live',()=>execute('resync'));bind('test',()=>execute('test'));
$('interval').onchange=()=>execute('maintenance',{interval_seconds:Number($('interval').value)}).catch(()=>{});
function openPage(page){window.open('/'+page+'#key='+encodeURIComponent(key),'_blank','noopener');}
bind('calibration',()=>{if((advanced.peers||[]).length!==1){notice('Для микрофонного замера подключите только одну Станцию.',true);return;}openPage('calibration.html');});
bind('legacy',()=>openPage('index.html'));
bind('diagnostic',async()=>{const report=await request('/api/diagnostic'),u=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=el('a');a.href=u;a.download='YandexStationAdvanced-diagnostic.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;const data=new FormData();data.append('file',file);try{const r=await fetch('/api/upload',{method:'POST',headers:{'X-Bridge-Key':key},body:data});const b=await r.json();if(!r.ok)throw Error(b.error);notice('Команда воспроизведения отправлена группе.');}catch(e){notice(e.message,true);}finally{$('file').value='';}};
bind('quit',async()=>{await execute('shutdown');notice('Приложение завершено. Эту вкладку можно закрыть.');clearInterval(timer);});
const timer=setInterval(poll,1100);poll();
